### ISSUE TITLE
RBAC权限控制

### ISSUE THREAD

**Issue by lsm1787569696** [vmeta42/neodata#51]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by liyanq528** [comment]
目前增加了登录功能，利用后台提供的API，验证用户是否有权限登录。
PR #70

**Comment by huhu-tiger** [comment]
后端接口代码[link](https://github.com/vmeta42/metadb/pull/71/commits/19dbe9df2e37d1e51505d2ae98b6c9a95c4d7688)
