### ISSUE TITLE
Mongodb分片集群方式及相关文档

### ISSUE THREAD

**Issue by Ada-pro** [vmeta42/neodata#61]

**Comment by huhu-tiger** [comment]
更改集群为分片模式, 并将mongodb 版本为6.0.x

**Comment by huhu-tiger** [comment]
已提交[link](https://github.com/vmeta42/metadb/commit/f2dd5ca3bbf76721b7fb03dc6f849657bd81903a)
[link](https://github.com/vmeta42/metadb/pull/59/commits)
